[package]
name = "moon-lunik"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lunik"
path = "src/main.rs"

[dependencies]
serde = "1.0.203"
serde_json_lenient = "0.2.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
